### ISSUE TITLE
Compatibility with X9DAi

### ISSUE THREAD

**Issue by NikosAlexandris** [putnam/superfans#2]
Any chance to get this working with the X9DAi motherboard (on a 7047A-T system)?

I get the following:
```
❯ ./superfans status
Error: Problem running ipmitool
Command: ipmitool raw 0x30 0x45 0x00
Return code: 1
Output: Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
```

OS:
Funtoo-Linux, kernel 5.1.0-pf7

Software versions:
- openipmi 2.0.27-r1
- ipmitool 1.8.18-r1

Thank you.

**Comment by putnam** [comment]
This workstation board unfortunately doesn’t have IPMI on board. So there’s
no way to control the fans over IPMI or through the BMC. You may be able to
use a more generic fan control tool that works with the BIOS but it’s
outside the scope of this tool. Though, if you do find something that
works, I’ll add it to the documentation.

**Comment by putnam** [comment]
FWIW, there's a discussion about this here with a link to SuperDoctor for Linux which may be useful for you:
https://www.reddit.com/r/homelab/comments/80yn4y/need_help_with_supermicro_motherboard_pwm_fans/

**Comment by NikosAlexandris** [comment]
> FWIW, there's a discussion about this here with a link to SuperDoctor for Linux which may be useful for you:
> https://www.reddit.com/r/homelab/comments/80yn4y/need_help_with_supermicro_motherboard_pwm_fans/

For the records, I managed to run SuperDoctor5. I got into the web interface. Nice overview. No way to control, however, the fans speeds -- after a quick look.
